openapi: 3.0.0
info:
  title: BookExchange API
  description: This is a simple API
  contact:
    email: yeejiac@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/yeejiac/BookExchange/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /api/bookgroup:
    get:
      tags:
      - developers
      summary: searches bookgroup
      description: "By passing in the appropriate options, you can search for\navailable\
        \ bookgroup in the system\n"
      operationId: searchbookgroup
      parameters:
      - name: searchString
        in: query
        description: pass an optional search string for looking up inventory
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: skip
        in: query
        description: number of records to skip for pagination
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int32
      - name: limit
        in: query
        description: maximum number of records to return
        required: false
        style: form
        explode: true
        schema:
          maximum: 50
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExchangeGroup'
                x-content-type: application/json
        "400":
          description: bad input parameter
    put:
      tags:
      - developers
      summary: modify an inventory item
      description: Adds an item to the system
      operationId: modifybookgroup
      requestBody:
        description: Bookgroup item to modify
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExchangeGroup'
      responses:
        "201":
          description: item created
        "400":
          description: "invalid input, object invalid"
        "409":
          description: an existing item already exists
    post:
      tags:
      - developers
      summary: adds an inventory item
      description: Adds an item to the system
      operationId: addInventory
      requestBody:
        description: Bookgroup item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExchangeGroup'
      responses:
        "201":
          description: item created
        "400":
          description: "invalid input, object invalid"
        "409":
          description: an existing item already exists
    delete:
      tags:
      - developers
      summary: adds an inventory item
      description: Adds an item to the system
      operationId: deleteInventory
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExchangeGroup'
                x-content-type: application/json
        "400":
          description: bad input parameter
components:
  schemas:
    ExchangeGroup:
      required:
      - catelog
      - establishtime
      - expiretime
      - groupid
      - groupname
      - holder
      - privacy
      type: object
      properties:
        groupid:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        groupname:
          type: string
          example: Widget Adapter
        establishtime:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        expiretime:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        holder:
          $ref: '#/components/schemas/Holder'
        catelog:
          type: string
          example: Widget Adapter
        privacy:
          type: integer
      example:
        expiretime: 2016-08-29T09:12:33.001Z
        catelog: Widget Adapter
        establishtime: 2016-08-29T09:12:33.001Z
        groupid: d290f1ee-6c54-4b01-90e6-d701748f0851
        privacy: 6
        holder:
          name: ACME Corporation
          email: ""
          age: 0
        groupname: Widget Adapter
    Holder:
      required:
      - age
      - email
      - name
      type: object
      properties:
        name:
          type: string
          example: ACME Corporation
        email:
          pattern: "\\\\.[Ii][Oo]$"
          type: string
          format: email
        age:
          type: integer
      example:
        name: ACME Corporation
        email: ""
        age: 0
